version: '3'
services:
  app:
    build: .
    command: ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-w", "4", "-b", "0.0.0.0:8000", "app.main:app"]
    ports:
      - "8000:8000"
  tests:
    build: .
    command: ["pytest"]
    depends_on:
      - app